"""Author NTRU+1152's schedulable kernels as data-flow, not register allocation.

Emits symbolic-register assembly (`V<name>`) for SLOTHY, following the form the
NTRU+864 campaign established in experiments/gt864-native-asm/generate.py.
SLOTHY does the register allocation and the scheduling; this file only fixes
which multiplications happen and in what algebraic order.

The C in the shipped package remains the oracle.  Every kernel here is checked
against it by a differential before any target's output is installed.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
Q, NEG_QINV, HALF = 3457, -12929, 1728
QREG, QI, HI, LO, ZERO = "v0", "v1", "v2", "v3", "v4"   # reserved from SLOTHY


class DAG:
    """Symbolic-register emitter.  `V<name>` is SLOTHY's symbolic syntax."""

    def __init__(self):
        self.lines = []
        self.seq = 0

    def emit(self, text):
        self.lines.append("    " + text)

    def label(self, name):
        self.lines.append(name + ":")

    def fresh(self):
        self.seq += 1
        return f"tmpv_{self.seq}"   # t0..tN are SLOTHY hint registers

    def constant(self, reg, value):
        """Constants live in *physical* registers, set up outside the optimized
        region and reserved from SLOTHY.  A symbolic register defined outside
        the region cannot be allocated, and recomputing them inside the loop
        would cost eight instructions per group."""
        self.emit(f"mov w8, #{value}")
        self.emit(f"dup {reg}.8h, w8")
        return reg

    def load(self, name, ptr, offset=0):
        self.emit(f"ldr Q<{name}>, [{ptr}, #{offset}]")
        return name

    def store(self, name, ptr, offset=0):
        self.emit(f"str Q<{name}>, [{ptr}, #{offset}]")

    @staticmethod
    def r(name, shape):
        """Physical registers are spelled directly; everything else symbolic."""
        return f"{name}.{shape}" if name.startswith("v") else f"V<{name}>.{shape}"

    def binary(self, op, a, b, shape="8h"):
        dst = self.fresh()
        self.emit(f"{op} {self.r(dst, shape)}, {self.r(a, shape)}, {self.r(b, shape)}")
        return dst

    def wide(self, a, b, acc=None):
        """smull/smlal pair: the 8-lane widening product, accumulating if given."""
        lo, hi = (self.fresh(), self.fresh()) if acc is None else acc
        op = "smull" if acc is None else "smlal"
        self.emit(f"{op} {self.r(lo, '4s')}, {self.r(a, '4h')}, {self.r(b, '4h')}")
        self.emit(f"{op}2 {self.r(hi, '4s')}, {self.r(a, '8h')}, {self.r(b, '8h')}")
        return lo, hi

    def wide_sub(self, a, b, acc):
        """smlsl/smlsl2 pair: subtract the 8-lane widening product."""
        lo, hi = acc
        self.emit(f"smlsl {self.r(lo, '4s')}, {self.r(a, '4h')}, {self.r(b, '4h')}")
        self.emit(f"smlsl2 {self.r(hi, '4s')}, {self.r(a, '8h')}, {self.r(b, '8h')}")
        return acc

    def neg(self, a):
        """SLOTHY's AArch64 model has no vector `neg`, so subtract from a zero
        register instead.  That is why v4 is reserved as well."""
        return self.binary("sub", ZERO, a)

    def fqmul(self, a, b):
        return self.redc(self.wide(a, b))

    def redc(self, acc):
        """Montgomery reduction of a widened accumulator, exactly the C's."""
        lo, hi = acc
        low = self.fresh()
        self.emit(f"uzp1 {self.r(low, '8h')}, {self.r(lo, '8h')}, {self.r(hi, '8h')}")
        quotient = self.binary("mul", low, QI)
        self.wide(quotient, QREG, acc)
        dst = self.fresh()
        self.emit(f"uzp2 {self.r(dst, '8h')}, {self.r(lo, '8h')}, {self.r(hi, '8h')}")
        return dst

    def normalize_d7(self, a):
        """D7's normalization as P24 established it: one conditional subtract.

        Every input is bounded by 2752 < 1728 + q, so exactly one of a-q, a+q
        or a lands in [-1728, 1728].  No multiply, which is the whole point --
        the multiply pipe is what bounds this kernel.
        """
        m = self.fresh()
        self.emit(f"cmgt {self.r(m, '8h')}, {self.r(a, '8h')}, {HI}.8h")
        self.emit(f"and {self.r(m, '16b')}, {self.r(m, '16b')}, {QREG}.16b")
        a = self.binary("sub", a, m)
        n = self.fresh()
        self.emit(f"cmgt {self.r(n, '8h')}, {LO}.8h, {self.r(a, '8h')}")
        self.emit(f"and {self.r(n, '16b')}, {self.r(n, '16b')}, {QREG}.16b")
        return self.binary("add", a, n)

    def text(self, symbol, header):
        body = "\n".join(self.lines)
        return f"""// Generated by dev/ntruplus1152_clean/generate.py; do not edit.
//
{header}
//
// live-in:  x0 out, x1 a, x2 b, x3 zeta table, x4 group counter
// live-out: x0-x3 advanced by their strides, memory at the original x0 written
// reserved: x18-x30, sp, v0-v3 and v8-v15.  Nothing is stashed, so the
//           callee-saved vector registers are off limits; the four constants are
//           physical because a symbolic register defined outside the optimized
//           region could not be allocated.  v4 is the zero vector, needed\n//           because the model has no vector `neg`.  That leaves v5-v7, v16-v31.
.text
.p2align 4
.global {symbol}
{symbol}:
{body}
"""


def basemul_rinv():
    """One Good-Thomas group of the degree-4 product with the R^-1 boundary.

    The zeta is pre-multiplied into b once, so the four output chains are
    independent four-term accumulations rather than
    cross -> reduce -> xzeta -> accumulate -> reduce in series.  P24 established
    that this is algebraically identical and is the form the official's
    instruction histogram matches.

    There is no normalization.  D7 added one because the output was bounded at
    2752, above the inverse's inherited input contract of 2497 -- but 2752 comes
    from assuming inputs on [0,4095].  The only caller feeds two `poly_frombytes`
    results and aborts unless both decode, so the inputs are canonical: with
    |a|,|b| <= q-1 the Montgomery bound is q/2 + 4(q-1)^2/2^16 = 2458, inside the
    contract, and P31 measures 2266 over 20,000 trials.  The official issues no
    normalization either, which is the whole of the gap P24 could not close.
    """
    d = DAG()
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.emit("mov x4, #36")
    d.label("basemul_rinv_loop")

    a = [d.load(f"a{i}", "x1", 16 * i) for i in range(4)]
    b = [d.load(f"b{i}", "x2", 16 * i) for i in range(4)]
    z = d.load("z", "x3")

    bz = [None] + [d.redc(d.wide(z, b[i])) for i in (1, 2, 3)]

    rows = [[(a[0], b[0]), (a[1], bz[3]), (a[2], bz[2]), (a[3], bz[1])],
            [(a[0], b[1]), (a[1], b[0]),  (a[2], bz[3]), (a[3], bz[2])],
            [(a[0], b[2]), (a[1], b[1]),  (a[2], b[0]),  (a[3], bz[3])],
            [(a[0], b[3]), (a[1], b[2]),  (a[2], b[1]),  (a[3], b[0])]]
    for i, row in enumerate(rows):
        acc = d.wide(*row[0])
        for x, y in row[1:]:
            d.wide(x, y, acc)
        d.store(d.redc(acc), "x0", 16 * i)

    d.emit("add x0, x0, #64")
    d.emit("add x1, x1, #64")
    d.emit("add x2, x2, #64")
    d.emit("add x3, x3, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne basemul_rinv_loop")
    d.emit("ret")
    return d.text("basemul_rinv_kernel",
                  "// NTRU+1152 degree-4 basemul with the R^-1 boundary, one group per\n"
                  "// iteration over the 36 Good-Thomas groups.")


def basemul_rinv_lane():
    """basemul_rinv writing the inverse's (component, half) lane basis directly.

    One iteration takes group k (half 0) and group k + 18 (half 1), which share
    (j, tg) = (k // 2, k % 2), and writes the 128 bytes at 128k that
    p65_rebase used to produce: for u = 0..7, c0h0 c1h0 c2h0 c3h0 c0h1 c1h1
    c2h1 c3h1.  The transpose has three levels.  The first is free: the
    Montgomery narrowing uzp2(lo, hi) of one component becomes
    trn2(c, c + 1), which narrows two components at once into (c, c + 1) pairs
    of 32-bit lanes.  zip.4s and zip.2d do the other two (P126).

    Two groups need more than the 19 free registers, so d8-d15 are stashed
    around the loop and v8-v15 are available to SLOTHY.  The 208-instruction
    body does not pipeline within SLOTHY's time limit; it is scheduled with
    --no-pipeline.  P126 also tried one group per iteration, storing each
    half's 8-byte words with str d / st1 {.d}[1]: two fewer permutes per group,
    but the lane stores cost the A76 about 2.9 cycles each.
    """
    d = DAG()
    d.emit("stp d8, d9, [sp, #-64]!")
    d.emit("stp d10, d11, [sp, #16]")
    d.emit("stp d12, d13, [sp, #32]")
    d.emit("stp d14, d15, [sp, #48]")
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.emit("mov x4, #18")
    d.label("basemul_rinv_lane_loop")

    pairs = []                                    # [half][pair] -> (lo, hi)
    for half in (0, 1):
        off, zoff = 1152 * half, 288 * half
        a = [d.load(f"a{half}{i}", "x1", off + 16 * i) for i in range(4)]
        b = [d.load(f"b{half}{i}", "x2", off + 16 * i) for i in range(4)]
        z = d.load(f"z{half}", "x3", zoff)
        bz = [None] + [d.redc(d.wide(z, b[i])) for i in (1, 2, 3)]
        rows = [[(a[0], b[0]), (a[1], bz[3]), (a[2], bz[2]), (a[3], bz[1])],
                [(a[0], b[1]), (a[1], b[0]),  (a[2], bz[3]), (a[3], bz[2])],
                [(a[0], b[2]), (a[1], b[1]),  (a[2], b[0]),  (a[3], bz[3])],
                [(a[0], b[3]), (a[1], b[2]),  (a[2], b[1]),  (a[3], b[0])]]
        accs = []
        for row in rows:
            acc = d.wide(*row[0])
            for x, y in row[1:]:
                d.wide(x, y, acc)
            lo, hi = acc                          # Montgomery step, narrowing deferred
            low = d.fresh()
            d.emit(f"uzp1 {d.r(low, '8h')}, {d.r(lo, '8h')}, {d.r(hi, '8h')}")
            d.wide(d.binary("mul", low, QI), QREG, acc)
            accs.append(acc)
        pairs.append([(d.binary("trn2", accs[c][0], accs[c + 1][0]),
                       d.binary("trn2", accs[c][1], accs[c + 1][1])) for c in (0, 2)])

    for part in (0, 1):                           # 0: u = 0..3 (low accumulators), 1: u = 4..7
        A = [pairs[0][0][part], pairs[0][1][part], pairs[1][0][part], pairs[1][1][part]]
        for k, op in enumerate(("zip1", "zip2")):
            h0 = d.binary(op, A[0], A[1], "4s")       # u = 2k, 2k+1 of half 0, as 64-bit lanes
            h1 = d.binary(op, A[2], A[3], "4s")
            d.store(d.binary("zip1", h0, h1, "2d"), "x0", 64 * part + 32 * k)
            d.store(d.binary("zip2", h0, h1, "2d"), "x0", 64 * part + 32 * k + 16)

    d.emit("add x0, x0, #128")
    d.emit("add x1, x1, #64")
    d.emit("add x2, x2, #64")
    d.emit("add x3, x3, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne basemul_rinv_lane_loop")
    d.emit("ldp d14, d15, [sp, #48]")
    d.emit("ldp d12, d13, [sp, #32]")
    d.emit("ldp d10, d11, [sp, #16]")
    d.emit("ldp d8, d9, [sp], #64")
    d.emit("ret")
    text = d.text("basemul_rinv_lane_kernel",
                  "// NTRU+1152 degree-4 basemul with the R^-1 boundary, two groups (the\n"
                  "// two halves of one (j, tg)) per iteration, stored in the inverse's\n"
                  "// (component, half) lane basis.")
    return text.replace("// reserved: x18-x30, sp, v0-v3 and v8-v15.  Nothing is stashed, so the\n"
                        "//           callee-saved vector registers are off limits;",
                        "// reserved: x18-x30, sp, v0-v4.  d8-d15 are stashed around the loop,\n"
                        "//           so v8-v15 are free;").replace(
                        "That leaves v5-v7, v16-v31.", "That leaves v5-v31.")


def baseinv_num():
    """The quartic adjugate and the scalar norm, one Good-Thomas group.

    X^4 - zeta is a quadratic tower: with u = X^2 and u^2 = zeta, the element
    a = (a0 + a2 u) + X(a1 + a3 u) lives in R[X]/(X^2 - u) over
    R = Z_q[u]/(u^2 - zeta), so the inverse is two nested quadratic
    conjugations.  t0 and t1 carry the inner conjugate, t2 its zeta twist, and
    the norm t0^2 - t1 t2 is the scalar that the batch inversion later inverts.
    """
    d = DAG()
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.emit("mov x4, #36")
    d.label("baseinv_num_loop")

    a = [d.load(f"a{i}", "x2", 16 * i) for i in range(4)]
    z = d.load("z", "x3")

    # t0 = a2^2 - 2 a1 a3 ;  t1 = a3^2
    acc = d.wide(a[2], a[2])
    d.wide_sub(a[1], a[3], acc)
    d.wide_sub(a[1], a[3], acc)
    t0 = d.redc(acc)
    t1 = d.fqmul(a[3], a[3])

    # t0 = a0^2 + zeta t0 ;  t1 = a1^2 + zeta t1 - 2 a0 a2
    acc = d.wide(a[0], a[0])
    d.wide(t0, z, acc)
    t0 = d.redc(acc)

    acc = d.wide(a[1], a[1])
    d.wide(t1, z, acc)
    d.wide_sub(a[0], a[2], acc)
    d.wide_sub(a[0], a[2], acc)
    t1 = d.redc(acc)

    t2 = d.fqmul(t1, z)

    # norm = t0^2 - t1 t2, the 8 lanes the batch inversion consumes
    acc = d.wide(t0, t0)
    d.wide_sub(t1, t2, acc)
    d.store(d.redc(acc), "x1")

    for i, (p, q_, r_, s_) in enumerate([(a[0], t0, a[2], t2),
                                         (a[3], t2, a[1], t0),
                                         (a[2], t0, a[0], t1),
                                         (a[1], t1, a[3], t0)]):
        acc = d.wide(p, q_)
        d.wide(r_, s_, acc)
        d.store(d.redc(acc), "x0", 16 * i)

    d.emit("add x0, x0, #64")
    d.emit("add x1, x1, #16")
    d.emit("add x2, x2, #64")
    d.emit("add x3, x3, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne baseinv_num_loop")
    d.emit("ret")
    return d.text("baseinv_num_kernel",
                  "// NTRU+1152 BaseInv numerator: the quartic adjugate into x0 and the\n"
                  "// scalar norm into x1, one group per iteration.\n"
                  "//\n"
                  "// x1 is the 36 x 8 norm array the batch inversion consumes.")


def baseinv_finish():
    """Apply the inverted norms with the +,-,+,- conjugation signs.

    The alternating sign is the deferred odd-degree negation of the conjugate,
    folded into the final scaling rather than applied earlier.
    """
    d = DAG()
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.emit(f"movi {ZERO}.16b, #0")
    d.emit("mov x4, #36")
    d.label("baseinv_finish_loop")

    pden = d.load("pden", "x1")
    mden = d.neg(pden)
    for i in range(4):
        r = d.load(f"r{i}", "x0", 16 * i)
        d.store(d.fqmul(r, pden if i % 2 == 0 else mden), "x0", 16 * i)

    d.emit("add x0, x0, #64")
    d.emit("add x1, x1, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne baseinv_finish_loop")
    d.emit("ret")
    return d.text("baseinv_finish_kernel",
                  "// NTRU+1152 BaseInv finish: scale the adjugate at x0 by the inverted\n"
                  "// norms at x1, with the +,-,+,- conjugation signs.")


KERNELS = {"basemul_rinv": basemul_rinv,
           "basemul_rinv_lane": basemul_rinv_lane,
           "baseinv_num": baseinv_num,
           "baseinv_finish": baseinv_finish}

if __name__ == "__main__":
    (HERE / "src").mkdir(exist_ok=True)
    for name, fn in KERNELS.items():
        p = HERE / "src" / f"{name}.sym.S"
        p.write_text(fn())
        n = sum(1 for l in p.read_text().splitlines() if l.startswith("    ") and not l.strip().startswith("//"))
        print(f"wrote {p.relative_to(HERE.parent)}: {n} instructions")
