"""Author NTRU+1152's schedulable kernels as data-flow, not register allocation.

Emits symbolic-register assembly (`V<name>`) for SLOTHY, following the form the
NTRU+864 campaign established in experiments/gt864-native-asm/generate.py.
SLOTHY does the register allocation and the scheduling; this file only fixes
which multiplications happen and in what algebraic order.

The C in the shipped package remains the oracle.  Every kernel here is checked
against it by a differential before any target's output is installed.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
Q, NEG_QINV, HALF = 3457, -12929, 1728
QREG, QI, HI, LO, ZERO = "v0", "v1", "v2", "v3", "v4"   # reserved from SLOTHY


class DAG:
    """Symbolic-register emitter.  `V<name>` is SLOTHY's symbolic syntax."""

    def __init__(self):
        self.lines = []
        self.seq = 0

    def emit(self, text):
        self.lines.append("    " + text)

    def label(self, name):
        self.lines.append(name + ":")

    def fresh(self):
        self.seq += 1
        return f"tmpv_{self.seq}"   # t0..tN are SLOTHY hint registers

    def constant(self, reg, value):
        """Constants live in *physical* registers, set up outside the optimized
        region and reserved from SLOTHY.  A symbolic register defined outside
        the region cannot be allocated, and recomputing them inside the loop
        would cost eight instructions per group."""
        self.emit(f"mov w8, #{value}")
        self.emit(f"dup {reg}.8h, w8")
        return reg

    def load(self, name, ptr, offset=0):
        self.emit(f"ldr Q<{name}>, [{ptr}, #{offset}]")
        return name

    def store(self, name, ptr, offset=0):
        self.emit(f"str Q<{name}>, [{ptr}, #{offset}]")

    @staticmethod
    def r(name, shape):
        """Physical registers are spelled directly; everything else symbolic."""
        return f"{name}.{shape}" if name.startswith("v") else f"V<{name}>.{shape}"

    def binary(self, op, a, b, shape="8h"):
        dst = self.fresh()
        self.emit(f"{op} {self.r(dst, shape)}, {self.r(a, shape)}, {self.r(b, shape)}")
        return dst

    def wide(self, a, b, acc=None):
        """smull/smlal pair: the 8-lane widening product, accumulating if given."""
        lo, hi = (self.fresh(), self.fresh()) if acc is None else acc
        op = "smull" if acc is None else "smlal"
        self.emit(f"{op} {self.r(lo, '4s')}, {self.r(a, '4h')}, {self.r(b, '4h')}")
        self.emit(f"{op}2 {self.r(hi, '4s')}, {self.r(a, '8h')}, {self.r(b, '8h')}")
        return lo, hi

    def wide_sub(self, a, b, acc):
        """smlsl/smlsl2 pair: subtract the 8-lane widening product."""
        lo, hi = acc
        self.emit(f"smlsl {self.r(lo, '4s')}, {self.r(a, '4h')}, {self.r(b, '4h')}")
        self.emit(f"smlsl2 {self.r(hi, '4s')}, {self.r(a, '8h')}, {self.r(b, '8h')}")
        return acc

    def neg(self, a):
        """SLOTHY's AArch64 model has no vector `neg`, so subtract from a zero
        register instead.  That is why v4 is reserved as well."""
        return self.binary("sub", ZERO, a)

    def fqmul(self, a, b):
        return self.redc(self.wide(a, b))

    def redc(self, acc):
        """Montgomery reduction of a widened accumulator, exactly the C's."""
        lo, hi = acc
        low = self.fresh()
        self.emit(f"uzp1 {self.r(low, '8h')}, {self.r(lo, '8h')}, {self.r(hi, '8h')}")
        quotient = self.binary("mul", low, QI)
        self.wide(quotient, QREG, acc)
        dst = self.fresh()
        self.emit(f"uzp2 {self.r(dst, '8h')}, {self.r(lo, '8h')}, {self.r(hi, '8h')}")
        return dst

    def normalize_d7(self, a):
        """D7's normalization as P24 established it: one conditional subtract.

        Every input is bounded by 2752 < 1728 + q, so exactly one of a-q, a+q
        or a lands in [-1728, 1728].  No multiply, which is the whole point --
        the multiply pipe is what bounds this kernel.
        """
        m = self.fresh()
        self.emit(f"cmgt {self.r(m, '8h')}, {self.r(a, '8h')}, {HI}.8h")
        self.emit(f"and {self.r(m, '16b')}, {self.r(m, '16b')}, {QREG}.16b")
        a = self.binary("sub", a, m)
        n = self.fresh()
        self.emit(f"cmgt {self.r(n, '8h')}, {LO}.8h, {self.r(a, '8h')}")
        self.emit(f"and {self.r(n, '16b')}, {self.r(n, '16b')}, {QREG}.16b")
        return self.binary("add", a, n)

    def text(self, symbol, header):
        body = "\n".join(self.lines)
        return f"""// Generated by dev/ntruplus1152_clean/generate.py; do not edit.
//
{header}
//
// live-in:  x0 out, x1 a, x2 b, x3 zeta table, x4 group counter
// live-out: x0-x3 advanced by their strides, memory at the original x0 written
// reserved: x18-x30, sp, v0-v3 and v8-v15.  Nothing is stashed, so the
//           callee-saved vector registers are off limits; the four constants are
//           physical because a symbolic register defined outside the optimized
//           region could not be allocated.  v4 is the zero vector, needed\n//           because the model has no vector `neg`.  That leaves v5-v7, v16-v31.
.text
.global {symbol}
{symbol}:
{body}
"""


def basemul_rinv():
    """One Good-Thomas group of the degree-4 product with the R^-1 boundary.

    The zeta is pre-multiplied into b once, so the four output chains are
    independent four-term accumulations rather than
    cross -> reduce -> xzeta -> accumulate -> reduce in series.  P24 established
    that this is algebraically identical and is the form the official's
    instruction histogram matches.
    """
    d = DAG()
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.constant(HI, HALF)
    d.constant(LO, -HALF)
    d.emit("mov x4, #36")
    d.label("basemul_rinv_loop")

    a = [d.load(f"a{i}", "x1", 16 * i) for i in range(4)]
    b = [d.load(f"b{i}", "x2", 16 * i) for i in range(4)]
    z = d.load("z", "x3")

    bz = [None] + [d.redc(d.wide(z, b[i])) for i in (1, 2, 3)]

    rows = [[(a[0], b[0]), (a[1], bz[3]), (a[2], bz[2]), (a[3], bz[1])],
            [(a[0], b[1]), (a[1], b[0]),  (a[2], bz[3]), (a[3], bz[2])],
            [(a[0], b[2]), (a[1], b[1]),  (a[2], b[0]),  (a[3], bz[3])],
            [(a[0], b[3]), (a[1], b[2]),  (a[2], b[1]),  (a[3], b[0])]]
    for i, row in enumerate(rows):
        acc = d.wide(*row[0])
        for x, y in row[1:]:
            d.wide(x, y, acc)
        d.store(d.normalize_d7(d.redc(acc)), "x0", 16 * i)

    d.emit("add x0, x0, #64")
    d.emit("add x1, x1, #64")
    d.emit("add x2, x2, #64")
    d.emit("add x3, x3, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne basemul_rinv_loop")
    d.emit("ret")
    return d.text("basemul_rinv_kernel",
                  "// NTRU+1152 degree-4 basemul with the R^-1 boundary, one group per\n"
                  "// iteration over the 36 Good-Thomas groups.")


def baseinv_num():
    """The quartic adjugate and the scalar norm, one Good-Thomas group.

    X^4 - zeta is a quadratic tower: with u = X^2 and u^2 = zeta, the element
    a = (a0 + a2 u) + X(a1 + a3 u) lives in R[X]/(X^2 - u) over
    R = Z_q[u]/(u^2 - zeta), so the inverse is two nested quadratic
    conjugations.  t0 and t1 carry the inner conjugate, t2 its zeta twist, and
    the norm t0^2 - t1 t2 is the scalar that the batch inversion later inverts.
    """
    d = DAG()
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.emit("mov x4, #36")
    d.label("baseinv_num_loop")

    a = [d.load(f"a{i}", "x2", 16 * i) for i in range(4)]
    z = d.load("z", "x3")

    # t0 = a2^2 - 2 a1 a3 ;  t1 = a3^2
    acc = d.wide(a[2], a[2])
    d.wide_sub(a[1], a[3], acc)
    d.wide_sub(a[1], a[3], acc)
    t0 = d.redc(acc)
    t1 = d.fqmul(a[3], a[3])

    # t0 = a0^2 + zeta t0 ;  t1 = a1^2 + zeta t1 - 2 a0 a2
    acc = d.wide(a[0], a[0])
    d.wide(t0, z, acc)
    t0 = d.redc(acc)

    acc = d.wide(a[1], a[1])
    d.wide(t1, z, acc)
    d.wide_sub(a[0], a[2], acc)
    d.wide_sub(a[0], a[2], acc)
    t1 = d.redc(acc)

    t2 = d.fqmul(t1, z)

    # norm = t0^2 - t1 t2, the 8 lanes the batch inversion consumes
    acc = d.wide(t0, t0)
    d.wide_sub(t1, t2, acc)
    d.store(d.redc(acc), "x1")

    for i, (p, q_, r_, s_) in enumerate([(a[0], t0, a[2], t2),
                                         (a[3], t2, a[1], t0),
                                         (a[2], t0, a[0], t1),
                                         (a[1], t1, a[3], t0)]):
        acc = d.wide(p, q_)
        d.wide(r_, s_, acc)
        d.store(d.redc(acc), "x0", 16 * i)

    d.emit("add x0, x0, #64")
    d.emit("add x1, x1, #16")
    d.emit("add x2, x2, #64")
    d.emit("add x3, x3, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne baseinv_num_loop")
    d.emit("ret")
    return d.text("baseinv_num_kernel",
                  "// NTRU+1152 BaseInv numerator: the quartic adjugate into x0 and the\n"
                  "// scalar norm into x1, one group per iteration.\n"
                  "//\n"
                  "// x1 is the 36 x 8 norm array the batch inversion consumes.")


def baseinv_finish():
    """Apply the inverted norms with the +,-,+,- conjugation signs.

    The alternating sign is the deferred odd-degree negation of the conjugate,
    folded into the final scaling rather than applied earlier.
    """
    d = DAG()
    d.constant(QREG, Q)
    d.constant(QI, NEG_QINV)
    d.emit(f"movi {ZERO}.16b, #0")
    d.emit("mov x4, #36")
    d.label("baseinv_finish_loop")

    pden = d.load("pden", "x1")
    mden = d.neg(pden)
    for i in range(4):
        r = d.load(f"r{i}", "x0", 16 * i)
        d.store(d.fqmul(r, pden if i % 2 == 0 else mden), "x0", 16 * i)

    d.emit("add x0, x0, #64")
    d.emit("add x1, x1, #16")
    d.emit("subs x4, x4, #1")
    d.emit("b.ne baseinv_finish_loop")
    d.emit("ret")
    return d.text("baseinv_finish_kernel",
                  "// NTRU+1152 BaseInv finish: scale the adjugate at x0 by the inverted\n"
                  "// norms at x1, with the +,-,+,- conjugation signs.")


KERNELS = {"basemul_rinv": basemul_rinv,
           "baseinv_num": baseinv_num,
           "baseinv_finish": baseinv_finish}

if __name__ == "__main__":
    (HERE / "src").mkdir(exist_ok=True)
    for name, fn in KERNELS.items():
        p = HERE / "src" / f"{name}.sym.S"
        p.write_text(fn())
        n = sum(1 for l in p.read_text().splitlines() if l.startswith("    ") and not l.strip().startswith("//"))
        print(f"wrote {p.relative_to(HERE.parent)}: {n} instructions")
