#!/usr/bin/env python3
"""Materialize the accepted AArch64 implementation as a SUPERCOP leaf.

NTRU+768 needs more than NTRU+864's and NTRU+1152's equivalents because its
sources live in `internal/`, `asm/` and `asm/internal/` while a SUPERCOP leaf is
flat.  Three things follow from that:

  * every path is flattened to its basename, and quoted includes are rewritten
    to match;
  * `internal/ntt.h` and `./ntt.h` are different headers with the same
    basename, so the internal one is exported as `internal_ntt.h`.  Which one a
    quoted `"ntt.h"` meant depends on where the including file was, so the
    rewrite is applied per source directory, not globally;
  * the three public entry points are defined in ASSEMBLY, by kem_api.S, which
    wraps the C `crypto_kem_*_internal` functions to preserve d8-d15 across the
    public boundary.  SUPERCOP namespaces through a C header, which cannot
    reach a symbol defined in assembly, so prepending `crypto_kem.h` to kem.c
    is not enough on its own: the assembly names are renamed at export time and
    a generated adapter.c bridges SUPERCOP's namespaced C names to them.  A
    leaf packaged without that bridge compiles cleanly and is then skipped,
    with no try row and no error, because the namespaced entry points do not
    exist.

CE/f1600.S and CE/fips202.c are not exported: the v8.4-A backend is selected by
__ARM_FEATURE_SHA3, and the benchmark host has no FEAT_SHA3, so the portable
sponge is what gets measured either way.
"""
from pathlib import Path
import argparse, filecmp, re, shutil, subprocess, tempfile

ROOT = Path(__file__).resolve().parents[1]

C_SOURCES = (
    "kem.c", "symmetric.c", "NO_CE/fips202.c",
    "internal/keygen.c", "internal/keygen_lambda.c", "internal/basemul_lambda.c",
    "internal/decap_verify.c", "internal/ntt_scratch.c",
)
ASM_SOURCES = (
    "asm/ntt.S", "asm/invntt.S", "asm/base.S", "asm/pack.S", "asm/cbd.S",
    "asm/support.S", "asm/kem_api.S",
    "asm/internal/unpack.S", "asm/internal/keygen_baseinv_prepare.S",
    "asm/internal/keygen_baseinv_tree.S", "asm/internal/keygen_baseinv_finish.S",
    "asm/internal/keygen_pack.S", "asm/internal/fqinv.S",
    "asm/internal/encap_muladd.S", "asm/internal/decap_verify.S",
    "asm/internal/decap_packed64.S", "asm/internal/decap_add.S",
    "asm/internal/decap_base.S", "asm/internal/decap_ntt.S",
    "asm/internal/decap_pack.S", "asm/internal/decap_forward.S",
)
HEADERS = (
    "api.h", "params.h", "poly.h", "ntt.h", "symmetric.h",
    "NO_CE/fips202.h",
    "internal/keygen.h", "internal/decap_verify.h", "internal/layout.h",
    "internal/secure_clear.h", "internal/ntt.h",
)
RENAMED = {"internal/ntt.h": "internal_ntt.h"}

INCLUDE = re.compile(r'(#\s*include\s+")([^"]+)(")')


def flat_name(path: str) -> str:
    return RENAMED.get(path, Path(path).name)


def rewrite_includes(text: str, source: str) -> str:
    """Rewrite quoted includes for the flattened layout.

    `internal_dir` decides what a bare "ntt.h" meant: inside internal/ it is
    internal/ntt.h, at the root it is ./ntt.h.
    """
    internal_dir = source.startswith("internal/") or source.startswith("asm/internal/")

    def sub(m):
        target = m.group(2)
        if target in RENAMED:
            return m.group(1) + RENAMED[target] + m.group(3)
        if target == "ntt.h" and internal_dir:
            return m.group(1) + RENAMED["internal/ntt.h"] + m.group(3)
        return m.group(1) + Path(target).name + m.group(3)

    return INCLUDE.sub(sub, text)


def preprocess(source: Path) -> bytes:
    return subprocess.check_output([
        "cc", "-E", "-P", "-x", "assembler-with-cpp",
        "-U__APPLE__", "-D__ELF__=1",
        f"-I{ROOT}", f"-I{ROOT}/internal", str(source),
    ])


PUBLIC_ENTRIES = ("crypto_kem_keypair", "crypto_kem_enc", "crypto_kem_dec")
EXPORT_PREFIX = "gt768_export_"

ADAPTER = """#include "crypto_kem.h"

/* Generated by scripts/export_supercop.py.  kem_api.S defines the public entry
 * points in assembly, where SUPERCOP's C-header namespacing cannot reach them;
 * the export renames those to %(prefix)s* and this bridges the namespaced C
 * names onto them. */
extern int %(prefix)scrypto_kem_keypair(unsigned char *, unsigned char *);
extern int %(prefix)scrypto_kem_enc(unsigned char *, unsigned char *,
                                    const unsigned char *);
extern int %(prefix)scrypto_kem_dec(unsigned char *, const unsigned char *,
                                    const unsigned char *);

int crypto_kem_keypair(unsigned char *pk, unsigned char *sk)
{ return %(prefix)scrypto_kem_keypair(pk, sk); }

int crypto_kem_enc(unsigned char *ct, unsigned char *ss, const unsigned char *pk)
{ return %(prefix)scrypto_kem_enc(ct, ss, pk); }

int crypto_kem_dec(unsigned char *ss, const unsigned char *ct, const unsigned char *sk)
{ return %(prefix)scrypto_kem_dec(ss, ct, sk); }
""" % {"prefix": EXPORT_PREFIX}


def rename_public_asm(text: bytes) -> bytes:
    """Rename the assembly-defined public entries, leaving *_internal alone."""
    out = text.decode()
    for name in PUBLIC_ENTRIES:
        out, n = re.subn(rf'\b{name}\b(?!_internal)', EXPORT_PREFIX + name, out)
        if n == 0:
            raise SystemExit(f"export-check: {name} not found in kem_api.s")
    return out.encode()


def write_tree(destination: Path) -> None:
    destination.mkdir(parents=True)
    for name in C_SOURCES:
        text = rewrite_includes((ROOT / name).read_text(), name)
        (destination / flat_name(name)).write_text(text)
    (destination / "adapter.c").write_text(ADAPTER)
    for name in HEADERS:
        text = rewrite_includes((ROOT / name).read_text(), name)
        (destination / flat_name(name)).write_text(text)
    for name in ASM_SOURCES:
        rendered = preprocess(ROOT / name)
        if Path(name).name == "kem_api.S":
            rendered = rename_public_asm(rendered)
        (destination / Path(name).with_suffix(".s").name).write_bytes(rendered)
    shutil.copyfile(ROOT / "LICENSE", destination / "LICENSE")
    (destination / "architectures").write_text("aarch64\narmv8-a\n")
    (destination / "goal-constbranch").write_text("")
    (destination / "goal-constindex").write_text("")
    (destination / "implementors").write_text("Chen Pin-Hao and contributors\n")


def equal(left: Path, right: Path) -> bool:
    c = filecmp.dircmp(left, right)
    if c.left_only or c.right_only or c.diff_files:
        return False
    return all(equal(left / n, right / n) for n in c.common_dirs)


parser = argparse.ArgumentParser()
parser.add_argument("destination", type=Path, nargs="?")
parser.add_argument("--check", action="store_true")
parser.add_argument("--self-check", action="store_true")
args = parser.parse_args()

if args.self_check:
    with tempfile.TemporaryDirectory() as a, tempfile.TemporaryDirectory() as b:
        left, right = Path(a) / "aarch64", Path(b) / "aarch64"
        write_tree(left); write_tree(right)
        if not equal(left, right):
            raise SystemExit("export-check: nondeterministic output")
    print("export-check: deterministic regeneration pass")
    raise SystemExit(0)

if args.destination is None:
    parser.error("destination is required unless --self-check is used")

with tempfile.TemporaryDirectory() as tmp:
    generated = Path(tmp) / "aarch64"
    write_tree(generated)
    if args.check:
        if not args.destination.is_dir() or not equal(generated, args.destination):
            raise SystemExit("export-check: destination differs")
        print("export-check: deterministic match")
    else:
        if args.destination.exists():
            raise SystemExit("destination exists; choose a fresh path")
        shutil.copytree(generated, args.destination)
        print(f"exported {args.destination}")
