#ifndef BENCH_BUILD_CONFIG_H
#define BENCH_BUILD_CONFIG_H

#include <stdio.h>

#ifndef GT_PRODUCTION_VARIANT_NAME
#define GT_PRODUCTION_VARIANT_NAME "unknown"
#endif

#if defined(GT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP)
#define GT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP_VALUE 1
#else
#define GT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP_VALUE 0
#endif

#if defined(GT_PRODUCTION_USE_RMINUS1_DECAP)
#define GT_PRODUCTION_USE_RMINUS1_DECAP_VALUE 1
#else
#define GT_PRODUCTION_USE_RMINUS1_DECAP_VALUE 0
#endif

#if defined(GT_PRODUCTION_USE_BPQ_CQ_KEYGEN)
#define GT_PRODUCTION_USE_BPQ_CQ_KEYGEN_VALUE 1
#else
#define GT_PRODUCTION_USE_BPQ_CQ_KEYGEN_VALUE 0
#endif

#if defined(GT_PRODUCTION_USE_KEYGEN_CQ)
#define GT_PRODUCTION_USE_KEYGEN_CQ_VALUE 1
#else
#define GT_PRODUCTION_USE_KEYGEN_CQ_VALUE 0
#endif

#if defined(GT_EXPERIMENT_USE_KEYGEN_ALL_CQ)
#define GT_EXPERIMENT_USE_KEYGEN_ALL_CQ_VALUE 1
#else
#define GT_EXPERIMENT_USE_KEYGEN_ALL_CQ_VALUE 0
#endif

#if defined(GT_EXPERIMENT_USE_KEYGEN_DIRECT_BPQ_ENDPOINT)
#define GT_EXPERIMENT_USE_KEYGEN_DIRECT_BPQ_ENDPOINT_VALUE 1
#else
#define GT_EXPERIMENT_USE_KEYGEN_DIRECT_BPQ_ENDPOINT_VALUE 0
#endif

#if defined(GT_EXPERIMENT_USE_KEYGEN_DIRECT_CQ_ENDPOINT)
#define GT_EXPERIMENT_USE_KEYGEN_DIRECT_CQ_ENDPOINT_VALUE 1
#else
#define GT_EXPERIMENT_USE_KEYGEN_DIRECT_CQ_ENDPOINT_VALUE 0
#endif

#if defined(GT_EXPERIMENT_USE_KEYGEN_SHARED_NTT_CORE)
#define GT_EXPERIMENT_USE_KEYGEN_SHARED_NTT_CORE_VALUE 1
#else
#define GT_EXPERIMENT_USE_KEYGEN_SHARED_NTT_CORE_VALUE 0
#endif

#if defined(GT_PRODUCTION_USE_DECAP_CANONICAL_POINTWISE)
#define GT_PRODUCTION_USE_DECAP_CANONICAL_POINTWISE_VALUE 1
#else
#define GT_PRODUCTION_USE_DECAP_CANONICAL_POINTWISE_VALUE 0
#endif

#if defined(GT_PRODUCTION_DECAP_VERIFY_COMPACT)
#define GT_PRODUCTION_DECAP_VERIFY_PROFILE_VALUE "compact"
#elif defined(GT_PRODUCTION_DECAP_VERIFY_SPEED)
#define GT_PRODUCTION_DECAP_VERIFY_PROFILE_VALUE "speed"
#else
#define GT_PRODUCTION_DECAP_VERIFY_PROFILE_VALUE "unknown"
#endif

#if defined(GT_PRODUCTION_USE_CANONICAL_UNPACK_U1)
#define GT_PRODUCTION_USE_CANONICAL_UNPACK_U1_VALUE 1
#else
#define GT_PRODUCTION_USE_CANONICAL_UNPACK_U1_VALUE 0
#endif

#if defined(GT_PRODUCTION_USE_SCALED_KEYPAIR)
#define GT_PRODUCTION_USE_SCALED_KEYPAIR_VALUE 1
#else
#define GT_PRODUCTION_USE_SCALED_KEYPAIR_VALUE 0
#endif

#if defined(GT_BASEINV_USE_FQINV15_ASM)
#define GT_BASEINV_USE_FQINV15_ASM_VALUE 1
#else
#define GT_BASEINV_USE_FQINV15_ASM_VALUE 0
#endif

#if defined(GT_BASEINV_BATCH_USE_ASM_FINISH)
#define GT_BASEINV_BATCH_USE_ASM_FINISH_VALUE 1
#else
#define GT_BASEINV_BATCH_USE_ASM_FINISH_VALUE 0
#endif

#if defined(GT_BASEINV_USE_HIER_K8)
#define GT_BASEINV_USE_HIER_K8_VALUE 1
#else
#define GT_BASEINV_USE_HIER_K8_VALUE 0
#endif

#if defined(GT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3)
#define GT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3_VALUE 1
#else
#define GT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3_VALUE 0
#endif

#if defined(GT_BASEINV_USE_HIER_K8_TREE)
#define GT_BASEINV_USE_HIER_K8_TREE_VALUE 1
#else
#define GT_BASEINV_USE_HIER_K8_TREE_VALUE 0
#endif

#if defined(GT_BASEINV_USE_PAPER_HIER_K8)
#define GT_BASEINV_USE_PAPER_HIER_K8_VALUE 1
#else
#define GT_BASEINV_USE_PAPER_HIER_K8_VALUE 0
#endif

static void bench_print_gt_production_config(void)
{
  printf("build_config,GT_PRODUCTION_VARIANT=%s\n",
         GT_PRODUCTION_VARIANT_NAME);
  printf("build_config,GT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP=%d\n",
         GT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP_VALUE);
  printf("build_config,GT_PRODUCTION_USE_RMINUS1_DECAP=%d\n",
         GT_PRODUCTION_USE_RMINUS1_DECAP_VALUE);
  printf("build_config,GT_PRODUCTION_USE_BPQ_CQ_KEYGEN=%d\n",
         GT_PRODUCTION_USE_BPQ_CQ_KEYGEN_VALUE);
  printf("build_config,GT_PRODUCTION_USE_KEYGEN_CQ=%d\n",
         GT_PRODUCTION_USE_KEYGEN_CQ_VALUE);
  printf("build_config,GT_EXPERIMENT_USE_KEYGEN_ALL_CQ=%d\n",
         GT_EXPERIMENT_USE_KEYGEN_ALL_CQ_VALUE);
  printf("build_config,GT_EXPERIMENT_USE_KEYGEN_DIRECT_BPQ_ENDPOINT=%d\n",
         GT_EXPERIMENT_USE_KEYGEN_DIRECT_BPQ_ENDPOINT_VALUE);
  printf("build_config,GT_EXPERIMENT_USE_KEYGEN_DIRECT_CQ_ENDPOINT=%d\n",
         GT_EXPERIMENT_USE_KEYGEN_DIRECT_CQ_ENDPOINT_VALUE);
  printf("build_config,GT_EXPERIMENT_USE_KEYGEN_SHARED_NTT_CORE=%d\n",
         GT_EXPERIMENT_USE_KEYGEN_SHARED_NTT_CORE_VALUE);
  printf("build_config,GT_PRODUCTION_USE_DECAP_CANONICAL_POINTWISE=%d\n",
         GT_PRODUCTION_USE_DECAP_CANONICAL_POINTWISE_VALUE);
  printf("build_config,GT_PRODUCTION_DECAP_VERIFY_PROFILE=%s\n",
         GT_PRODUCTION_DECAP_VERIFY_PROFILE_VALUE);
  printf("build_config,GT_PRODUCTION_USE_CANONICAL_UNPACK_U1=%d\n",
         GT_PRODUCTION_USE_CANONICAL_UNPACK_U1_VALUE);
  printf("build_config,GT_PRODUCTION_USE_SCALED_KEYPAIR=%d\n",
         GT_PRODUCTION_USE_SCALED_KEYPAIR_VALUE);
  printf("build_config,GT_BASEINV_USE_FQINV15_ASM=%d\n",
         GT_BASEINV_USE_FQINV15_ASM_VALUE);
  printf("build_config,GT_BASEINV_BATCH_USE_ASM_FINISH=%d\n",
         GT_BASEINV_BATCH_USE_ASM_FINISH_VALUE);
  printf("build_config,GT_BASEINV_USE_HIER_K8=%d\n",
         GT_BASEINV_USE_HIER_K8_VALUE);
  printf("build_config,GT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3=%d\n",
         GT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3_VALUE);
  printf("build_config,GT_BASEINV_USE_HIER_K8_TREE=%d\n",
         GT_BASEINV_USE_HIER_K8_TREE_VALUE);
  printf("build_config,GT_BASEINV_USE_PAPER_HIER_K8=%d\n",
         GT_BASEINV_USE_PAPER_HIER_K8_VALUE);
}

#endif
