#define crypto_kem_keypair bench_crypto_kem_keypair_compact
#define crypto_kem_enc bench_crypto_kem_enc_compact
#define crypto_kem_dec bench_crypto_kem_dec_compact
#define gt_decap_verify_to_bytes gt_decap_verify_to_bytes_compact
#include "ntruplus/kem.c"
