#define crypto_kem_keypair bench_crypto_kem_keypair_speed
#define crypto_kem_enc bench_crypto_kem_enc_speed
#define crypto_kem_dec bench_crypto_kem_dec_speed
#define gt_decap_verify_to_bytes gt_decap_verify_to_bytes_speed
#include "ntruplus/kem.c"
