/* Generated by generate_pairs.py.  Do not edit. */
#ifndef NTRUPLUS1152_CODEC_PAIRS_H
#define NTRUPLUS1152_CODEC_PAIRS_H

#define CODEC_PAIRS 18

/* First group of each pair; the second is always this plus nine. */
static const unsigned char pair_group[CODEC_PAIRS] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 19, 20, 21, 22, 23, 24, 25, 26
};

/* Wire byte offset of the twelve-byte block held by lane k of pair p. */
static const unsigned short pair_wire[CODEC_PAIRS][8] = {
    {   0,  288,  576,   96,  384,  672,  192,  480},
    { 768,   48,  336,  624,  144,  432,  720,  240},
    { 528,  816,   24,  312,  600,  120,  408,  696},
    { 216,  504,  792,   72,  360,  648,  168,  456},
    { 744,  264,  552,  840,   12,  300,  588,  108},
    { 396,  684,  204,  492,  780,   60,  348,  636},
    { 156,  444,  732,  252,  540,  828,   36,  324},
    { 612,  132,  420,  708,  228,  516,  804,   84},
    { 372,  660,  180,  468,  756,  276,  564,  852},
    { 864, 1152, 1440,  960, 1248, 1536, 1056, 1344},
    {1632,  912, 1200, 1488, 1008, 1296, 1584, 1104},
    {1392, 1680,  888, 1176, 1464,  984, 1272, 1560},
    {1080, 1368, 1656,  936, 1224, 1512, 1032, 1320},
    {1608, 1128, 1416, 1704,  876, 1164, 1452,  972},
    {1260, 1548, 1068, 1356, 1644,  924, 1212, 1500},
    {1020, 1308, 1596, 1116, 1404, 1692,  900, 1188},
    {1476,  996, 1284, 1572, 1092, 1380, 1668,  948},
    {1236, 1524, 1044, 1332, 1620, 1140, 1428, 1716},
};

/* P130/P131 (gen_store_order.py): group processing order, lane order within
 * each group, and the store for each lane's 12-byte run -- 0: split stores,
 * 1: one 16-byte store at the run (garbage in the next run, written later),
 * 2: one 16-byte store ending at the run (garbage in the previous run, written
 * later).  66 of the 144 runs take one store; the final bytes
 * are verified by simulating every write. */
static const unsigned char pair_order[CODEC_PAIRS] = {0, 1, 16, 8, 9, 17, 4, 6, 12, 13, 5, 14, 10, 15, 3, 2, 7, 11};
static const unsigned char pair_lane[CODEC_PAIRS][8] = {
    {5, 3, 7, 1, 2, 0, 6, 4},
    {7, 1, 4, 2, 3, 5, 0, 6},
    {0, 2, 1, 4, 3, 6, 5, 7},
    {4, 2, 7, 0, 5, 1, 6, 3},
    {1, 2, 7, 0, 4, 3, 5, 6},
    {5, 2, 6, 3, 4, 7, 1, 0},
    {0, 1, 2, 4, 3, 7, 5, 6},
    {4, 5, 2, 7, 6, 0, 3, 1},
    {4, 7, 1, 0, 5, 2, 6, 3},
    {7, 6, 2, 4, 0, 3, 5, 1},
    {4, 5, 2, 0, 7, 6, 3, 1},
    {0, 1, 2, 7, 5, 6, 3, 4},
    {3, 7, 1, 2, 5, 6, 4, 0},
    {6, 2, 7, 4, 0, 3, 1, 5},
    {1, 4, 2, 6, 0, 5, 7, 3},
    {5, 7, 6, 4, 3, 1, 0, 2},
    {2, 7, 6, 4, 1, 3, 0, 5},
    {4, 5, 1, 3, 0, 6, 7, 2},
};
static const unsigned char pair_store[CODEC_PAIRS][8] = {
    {1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1},
    {0, 0, 0, 0, 1, 1, 1, 1},
    {1, 1, 1, 1, 0, 0, 0, 0},
    {0, 0, 0, 0, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 1},
    {1, 1, 1, 1, 1, 1, 1, 1},
    {0, 0, 0, 0, 1, 1, 1, 1},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 1, 1, 1, 1},
    {1, 1, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0},
    {1, 1, 1, 1, 1, 1, 1, 1},
    {0, 0, 0, 0, 1, 0, 0, 0},
};

#endif
