static inline void gather4_f(uint16x8_t out[4],const void *src,const uint16_t *map) {
uint16x8_t v0=vdupq_n_u16(0);
uint16x8_t v1=vdupq_n_u16(0);
uint16x8_t v2=vdupq_n_u16(0);
uint16x8_t v3=vdupq_n_u16(0);
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[0]) : "memory");
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[8]) : "memory");
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[16]) : "memory");
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[24]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[1]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[9]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[17]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[25]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[2]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[10]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[18]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[26]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[3]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[11]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[19]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[27]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[4]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[12]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[20]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[28]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[5]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[13]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[21]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[29]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[6]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[14]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[22]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[30]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+2*map[7]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+2*map[15]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+2*map[23]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+2*map[31]) : "memory");
out[0]=v0;
out[1]=v1;
out[2]=v2;
out[3]=v3;
}
static inline void gather4_r(uint16x8_t out[4],const void *src,const uint16_t *map,const int16_t *shifts) {
uint16x8_t v0=vdupq_n_u16(0);
uint16x8_t v1=vdupq_n_u16(0);
uint16x8_t v2=vdupq_n_u16(0);
uint16x8_t v3=vdupq_n_u16(0);
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[0]) : "memory");
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[8]) : "memory");
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[16]) : "memory");
__asm__ volatile("ld1 {%0.h}[0], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[24]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[1]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[9]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[17]) : "memory");
__asm__ volatile("ld1 {%0.h}[1], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[25]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[2]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[10]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[18]) : "memory");
__asm__ volatile("ld1 {%0.h}[2], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[26]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[3]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[11]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[19]) : "memory");
__asm__ volatile("ld1 {%0.h}[3], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[27]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[4]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[12]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[20]) : "memory");
__asm__ volatile("ld1 {%0.h}[4], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[28]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[5]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[13]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[21]) : "memory");
__asm__ volatile("ld1 {%0.h}[5], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[29]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[6]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[14]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[22]) : "memory");
__asm__ volatile("ld1 {%0.h}[6], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[30]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v0) : "r"((const uint8_t*)src+map[7]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v1) : "r"((const uint8_t*)src+map[15]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v2) : "r"((const uint8_t*)src+map[23]) : "memory");
__asm__ volatile("ld1 {%0.h}[7], [%1]" : "+w"(v3) : "r"((const uint8_t*)src+map[31]) : "memory");
v0=vandq_u16(vshlq_u16(v0,vld1q_s16(shifts+0)),vdupq_n_u16(4095));
out[0]=v0;
v1=vandq_u16(vshlq_u16(v1,vld1q_s16(shifts+8)),vdupq_n_u16(4095));
out[1]=v1;
v2=vandq_u16(vshlq_u16(v2,vld1q_s16(shifts+16)),vdupq_n_u16(4095));
out[2]=v2;
v3=vandq_u16(vshlq_u16(v3,vld1q_s16(shifts+24)),vdupq_n_u16(4095));
out[3]=v3;
}
