#!/usr/bin/env python3
"""Write the mlkem-native-Keccak KEM overlays of Official NTRU+ AVX2 (768/864/1152).

Each parameter's current best Official-opt candidate is kept unchanged; the
new candidate is a preprocessor overlay that includes it after
common/official_opt_keccak/src/fips202_mlkem.h (shake256 -> mlk_shake256,
the vendored mlkem-native x1 C Keccak) and keccak_names.h (hash_f/g/h ->
ntruplus{N}_keccak_hash_{f,g,h}, defined by src/symmetric_keccak.c = the
Official symmetric.c on the same backend).  A keccak-only control applies
the same overlay to the pinned Official kem.c.

  768  base avx2-officialopt-lazy-freeze-768-exp001  src/kem_lazy_freeze2op.c
       -> avx2-officialopt-lazy-freeze-keccak-768-exp001  src/kem_lazy_freeze2op_keccak.c
  864  base avx2-officialopt-lazy-codec-864-exp002    src/kem_lazy_codec_direct.c
       -> avx2-officialopt-lazy-codec-keccak-864-exp001   src/kem_lazy_codec_direct_keccak.c
  1152 base avx2-officialopt-lazy-freeze-1152-exp001 src/kem_lazy_freeze2op.c
       -> avx2-officialopt-lazy-freeze-keccak-1152-exp001 src/kem_lazy_freeze2op_keccak.c
  all  control keccak-only (Official kem.c + mlkem-native Keccak)  src/kem_keccak.c

Gates enforced here: pinned sha256 of the Official kem.c / symmetric.c /
symmetric.h / fips202.h / util.h; the Official fips202.h include guard is
FIPS202_H and its shake256 macro names fips202avx_shake256 (the guard the
replacement header claims); the base overlay exists and its include chain
(overlay -> kem_lazy.c -> ...) calls shake256 exactly 2x (keypair genf/geng)
and hash_f/g/h exactly 2x each, with no other SHAKE/SHA3/Keccak identifier;
kem_lazy.c includes "fips202.h" and "symmetric.h"; deterministic output.

  generate_keccak_overlays.py --param 768 --experiment .           # write
  generate_keccak_overlays.py --param 768 --experiment . --check   # verify
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve()
COMMON = HERE.parents[1]
REPO = next(p for p in HERE.parents if (p / "bench/supercop.lock").exists())

# sha256 of the imported (never edited) SUPERCOP 20260831 crypto_kem/ntruplus{N}/avx2
# files; identical for all three parameter sets.
PINNED = {
    "kem.c": "368bb8f799566cf199960ffdc80e33acce0da5cfe141fffa248a21f221ae7f3f",
    "symmetric.c": "49e7faa9501e3ced6bf6c8da519782adcb32371295ce4f351ebdbf63399f9e0c",
    "symmetric.h": "d56d67dbf50c7b89de87eb5acbcfb11ece0fe90e7744762c0bc9a47350d80f65",
    "fips202.h": "c843fef66468b1fc4ef6662409f789051a27e96470ffa04648cb7146c3b68a8f",
    "fips202.c": "8b4059e2702f51e98c34c656132443b2ed3144afa1b295a588cb5a8d41aaf5a1",
    "util.h": "0b8aeae3b5d7bd6e215bcc5ae7fdcabe42c5dd824591f84122badedb3aea77f9",
}
PARAMS = {
    768: {"base": "kem_lazy_freeze2op", "base_name": "avx2-officialopt-lazy-freeze-768-exp001",
          "candidate": "avx2-officialopt-lazy-freeze-keccak-768-exp001"},
    864: {"base": "kem_lazy_codec_direct", "base_name": "avx2-officialopt-lazy-codec-864-exp002",
          "candidate": "avx2-officialopt-lazy-codec-keccak-864-exp001"},
    1152: {"base": "kem_lazy_freeze2op", "base_name": "avx2-officialopt-lazy-freeze-1152-exp001",
           "candidate": "avx2-officialopt-lazy-freeze-keccak-1152-exp001"},
}
EXPECTED_CALLS = {"shake256": 2, "hash_f": 2, "hash_g": 2, "hash_h": 2}
FORBIDDEN = re.compile(r"\b(shake128\w*|sha3_\w+|Keccak\w*|fips202avx_\w+|shake256_\w+)\b")
PREAMBLE = ('#include "util.h"\n'
            '#include "fips202_mlkem.h"\n'
            '#include "keccak_names.h"\n')


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def include_chain(path: Path, seen=None):
    """The overlay's local (quoted, same-directory or ../upstream) C sources."""
    seen = seen if seen is not None else []
    seen.append(path)
    for inc in re.findall(r'^\s*#\s*include\s+"([^"]+\.c)"', path.read_text(), flags=re.M):
        include_chain((path.parent / inc).resolve(), seen)
    return seen


def call_counts(sources):
    text = "".join(strip_comments(p.read_text()) for p in sources)
    counts = {name: len(re.findall(rf"\b{name}\s*\(", text)) for name in EXPECTED_CALLS}
    return counts, sorted(set(FORBIDDEN.findall(text)))


def header(param: int, what: str) -> str:
    return ("/*\n * GENERATED by common/official_opt_keccak/tools/generate_keccak_overlays.py"
            " -- do not edit.\n" + what +
            " * All SHAKE256 goes to the vendored mlkem-native x1 C Keccak\n"
            " * (third_party/mlkem-native-fips202-b3ba7b32): the 2 direct shake256 calls\n"
            " * (keypair genf/geng) via fips202_mlkem.h -> mlk_shake256, and the 2+2+2\n"
            " * hash_f/g/h calls via keccak_names.h -> ntruplus%d_keccak_hash_{f,g,h}\n"
            " * (common/official_opt_keccak/src/symmetric_keccak.c).  Preprocessor overlay;\n"
            " * the included KEM source is unchanged, so it and this variant can be\n"
            " * linked into one ELF.\n */\n" % param)


def generate(param: int, root: Path):
    upstream = root / "upstream/supercop-avx2"
    pins = {}
    for name, expected in PINNED.items():
        got = sha256((upstream / name).read_bytes())
        if got != expected:
            raise ValueError(f"pinned {name} sha256 mismatch: {got}")
        pins[name] = got
    fips = (upstream / "fips202.h").read_text()
    if not re.search(r"^#ifndef FIPS202_H\n#define FIPS202_H\n", fips, flags=re.M) or \
            "#define shake256 FIPS202AVX_NAMESPACE(shake256)" not in fips:
        raise ValueError("Official fips202.h guard / shake256 binding changed")
    kem_lazy = (root / "src/kem_lazy.c").read_text()
    for inc in ('#include "fips202.h"', '#include "symmetric.h"'):
        if inc not in kem_lazy:
            raise ValueError(f"src/kem_lazy.c lacks {inc}")
    cfg = PARAMS[param]
    base = root / f"src/{cfg['base']}.c"
    meta = {"parameter": f"NTRU+{param}", "pinned_upstream_sha256": pins,
            "base_candidate": cfg["base_name"], "candidate": cfg["candidate"],
            "control": "keccak-only (Official kem.c + mlkem-native Keccak)", "variants": {}}
    outputs = {}
    variants = {
        f"src/{cfg['base']}_keccak.c": (base, cfg["candidate"], (
            f" * NTRU+{param} AVX2 candidate {cfg['candidate']}: the base candidate\n"
            f" * {cfg['base_name']} (src/{cfg['base']}.c, unchanged) on mlkem-native Keccak.\n")),
        "src/kem_keccak.c": (upstream / "kem.c", "keccak-only control", (
            f" * NTRU+{param} AVX2 keccak-only control (diagnostic): the pinned Official\n"
            " * kem.c, unmodified, on mlkem-native Keccak.\n")),
    }
    for rel, (target, label, what) in variants.items():
        chain = include_chain(target)
        counts, forbidden = call_counts(chain)
        if counts != EXPECTED_CALLS or forbidden:
            raise ValueError(f"{rel}: unexpected SHAKE call sites {counts} / {forbidden}")
        inc = f"{target.name}" if target.parent == root / "src" else "../upstream/supercop-avx2/kem.c"
        outputs[root / rel] = header(param, what) + PREAMBLE + f'#include "{inc}"\n'
        meta["variants"][rel] = {"label": label, "includes": inc,
                                 "include_chain": [str(p.relative_to(root)) for p in chain],
                                 "include_chain_sha256": {str(p.relative_to(root)): sha256(p.read_bytes())
                                                          for p in chain},
                                 "call_sites": counts}
    return outputs, meta


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--param", type=int, choices=sorted(PARAMS), required=True)
    ap.add_argument("--experiment", type=Path, required=True)
    ap.add_argument("--check", action="store_true",
                    help="verify committed outputs equal regeneration; write nothing")
    ap.add_argument("--meta", type=Path, help="write the generation record (JSON) here")
    args = ap.parse_args()
    root = args.experiment.resolve()
    outputs, meta = generate(args.param, root)
    if (outputs, meta) != generate(args.param, root):
        raise ValueError("non-deterministic generation")
    meta["outputs_sha256"] = {str(p.relative_to(root)): sha256(t.encode()) for p, t in outputs.items()}
    meta["generator_sha256"] = sha256(HERE.read_bytes())
    meta["common_sha256"] = {str(p.relative_to(REPO)): sha256(p.read_bytes()) for p in (
        COMMON / "src/fips202_mlkem.h", COMMON / "src/keccak_names.h",
        COMMON / "src/symmetric_keccak.c", COMMON / "config/mlkem_native_config.h")}
    if args.check:
        bad = [str(p) for p, t in outputs.items() if not p.exists() or p.read_text() != t]
        if bad:
            print("MISMATCH vs regeneration: " + ", ".join(bad), file=sys.stderr)
            return 1
        verb = "ok"
    else:
        for p, t in outputs.items():
            p.write_text(t)
        verb = "wrote"
    for p, t in outputs.items():
        print(f"{verb} {p.relative_to(root)} sha256={sha256(t.encode())}")
    if args.meta:
        args.meta.parent.mkdir(parents=True, exist_ok=True)
        args.meta.write_text(json.dumps(meta, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
