#define poly_basemul stock_poly_basemul
#define _poly_basemul _stock_poly_basemul
#define poly_basemul_add stock_poly_basemul_add
#define _poly_basemul_add _stock_poly_basemul_add
#define poly_baseinv_1 stock_poly_baseinv_1
#define _poly_baseinv_1 _stock_poly_baseinv_1

#ifndef BENCH_PMU_STOCK_BASE_INCLUDE
#define BENCH_PMU_STOCK_BASE_INCLUDE "../asm/base.s"
#endif

#include BENCH_PMU_STOCK_BASE_INCLUDE
