#!/usr/bin/env python3
"""Write the NTRU+768 HT / R^2-fold KEM overlays (preprocessor only).

Base: avx2-officialopt-lazy-freeze-keccak-768-exp001 = src/kem_lazy_freeze2op_keccak.c
(mlkem-native Keccak headers + `#define poly_tobytes <freeze2op>` + kem_lazy.c).

  src/kem_lazy_freeze2op_keccak_ht.c         control ht_only     = base, Forward -> HT
  src/kem_lazy_r2fold_freeze2op_keccak.c     control r2fold_only = base on kem_lazy_r2fold.c
  src/kem_lazy_freeze2op_keccak_htinv.c      control htinv_only  = base, inverse NTT -> HT inverse
  src/kem_lazy_r2fold_freeze2op_keccak_ht.c  control ht_r2fold   = base + HT Forward + keygen R^2 fold
  src/kem_lazy_r2fold_freeze2op_keccak_ht_htinv.c
                                             candidate avx2-officialopt-lazy-freeze-keccak-ht-768-exp001
                                             = base + HT Forward + keygen R^2 fold + HT inverse NTT

The Forward rebinding is `#define ntruplus768_officialopt_ntt_caller_lazy
ntruplus768_officialopt_ntt_ht`, which renames the prototype and all 6 call
sites of kem_lazy.c (and of kem_lazy_r2fold.c, which keeps them unchanged);
the inverse rebinding `#define poly_invntt_scale ntruplus768_officialopt_invntt_ht`
renames the poly.h prototype and the single (Decap) call site.
Every included file stays byte-identical, so all variants link into one ELF.

  generate_ht_overlays.py --experiment . [--check]
"""
import argparse
import hashlib
import sys
from pathlib import Path

LAZY = "ntruplus768_officialopt_ntt_caller_lazy"
HT = "ntruplus768_officialopt_ntt_ht"
HTINV = "ntruplus768_officialopt_invntt_ht"
FREEZE = "ntruplus768_officialopt_tobytes_freeze2op"
PINS = {
    "src/kem_lazy.c": "ffd9165c36466c2ecc57e4a157a2a847dc9f19d1fc249ebbc9c1c46baa22fd7d",
    "src/kem_lazy_freeze2op.c": None,   # checked structurally below
    "src/kem_lazy_freeze2op_keccak.c": "930512bfdcf6d0efe8ebb3326755fa7bc270a210e3ff30b4c8ed39f7b76ec6b4",
}
HEAD = "/*\n * GENERATED by common/official_opt_ht/tools/generate_ht_overlays.py -- do not edit.\n"


def sha256(b):
    return hashlib.sha256(b).hexdigest()


def outputs(root):
    for rel, pin in PINS.items():
        data = (root / rel).read_bytes()
        if pin and sha256(data) != pin:
            raise ValueError(f"pinned input changed: {rel}")
    fz = (root / "src/kem_lazy_freeze2op.c").read_text()
    if f"#define poly_tobytes {FREEZE}\n#include \"kem_lazy.c\"\n" not in fz:
        raise ValueError("unexpected freeze2op overlay")
    kc = (root / "src/kem_lazy_freeze2op_keccak.c").read_text()
    keccak_prelude = '#include "util.h"\n#include "fips202_mlkem.h"\n#include "keccak_names.h"\n'
    if not kc.endswith(keccak_prelude + '#include "kem_lazy_freeze2op.c"\n'):
        raise ValueError("unexpected keccak overlay")
    lazy = (root / "src/kem_lazy.c").read_text()
    r2 = (root / "src/kem_lazy_r2fold.c").read_text()
    for name, text in (("kem_lazy.c", lazy), ("kem_lazy_r2fold.c", r2)):
        if text.count(LAZY) != 7 or text.count(f"void {LAZY}(poly *);") != 1:
            raise ValueError(f"{name}: expected 1 prototype + 6 Forward calls")
        if text.count("poly_invntt_scale(") != 1:
            raise ValueError(f"{name}: expected 1 inverse NTT call")
    ht_def = f"#define {LAZY} {HT}\n"
    inv_def = f"#define poly_invntt_scale {HTINV}\n"
    return {
        "src/kem_lazy_freeze2op_keccak_ht.c": HEAD +
        " * NTRU+768 AVX2 control ht_only: the base candidate avx2-officialopt-lazy-freeze-keccak-768-exp001\n"
        " * (src/kem_lazy_freeze2op_keccak.c, unchanged) with its 6 caller-lazy Forward calls\n"
        f" * bound to asm/{HT}.s (bit-identical output).  Diagnostic.\n */\n"
        + ht_def + '#include "kem_lazy_freeze2op_keccak.c"\n',
        "src/kem_lazy_r2fold_freeze2op_keccak.c": HEAD +
        " * NTRU+768 AVX2 control r2fold_only: the base candidate's overlay chain (mlkem-native\n"
        " * Keccak headers, 2-op-freeze poly_tobytes) on src/kem_lazy_r2fold.c (caller-lazy KEM\n"
        " * with the keygen R^2 fold) instead of src/kem_lazy.c.  Diagnostic.\n */\n"
        + keccak_prelude + f"#define poly_tobytes {FREEZE}\n" + '#include "kem_lazy_r2fold.c"\n',
        "src/kem_lazy_r2fold_freeze2op_keccak_ht.c": HEAD +
        " * NTRU+768 AVX2 control ht_r2fold (items 1+2): base candidate + HT Forward (6 calls)\n"
        " * + keygen R^2 fold (2 BaseInv, 2 keygen BaseMul).  Diagnostic.\n */\n"
        + ht_def + '#include "kem_lazy_r2fold_freeze2op_keccak.c"\n',
        "src/kem_lazy_freeze2op_keccak_htinv.c": HEAD +
        " * NTRU+768 AVX2 control htinv_only: the base candidate (src/kem_lazy_freeze2op_keccak.c,\n"
        f" * unchanged) with its Decap inverse NTT bound to asm/{HTINV}.s\n"
        " * (bit-identical to Official poly_invntt_scale).  Diagnostic.\n */\n"
        + inv_def + '#include "kem_lazy_freeze2op_keccak.c"\n',
        "src/kem_lazy_r2fold_freeze2op_keccak_ht_htinv.c": HEAD +
        " * NTRU+768 AVX2 candidate avx2-officialopt-lazy-freeze-keccak-ht-768-exp001: base\n"
        " * candidate + HT Forward (6 calls) + keygen R^2 fold (2 BaseInv, 2 keygen BaseMul)\n"
        " * + HT inverse NTT (1 Decap call).\n */\n"
        + inv_def + '#include "kem_lazy_r2fold_freeze2op_keccak_ht.c"\n',
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--experiment", type=Path, required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    root = args.experiment.resolve()
    outs = outputs(root)
    if outs != outputs(root):
        raise ValueError("non-deterministic")
    bad = []
    for rel, text in outs.items():
        p = root / rel
        if args.check:
            if not p.exists() or p.read_text() != text:
                bad.append(rel)
                continue
            print(f"ok {rel} sha256={sha256(text.encode())}")
        else:
            p.write_text(text)
            print(f"wrote {rel} sha256={sha256(text.encode())}")
    if bad:
        print("MISMATCH vs regeneration: " + ", ".join(bad), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
