#!/usr/bin/env python3
"""Generate the Inverse D / Shoup BaseMul KEM sources and overlays (NTRU+768 / 864 / 1152).

KEM bodies, from the committed src/kem_lazy_r2fold.c (the current-best KEM body: caller-lazy
Forward call sites + keygen R^2 fold) by exact, counted textual edits:

  src/kem_lazy_r2fold_invcrep.c        Decap `poly_invntt_scale(&m); poly_crepmod3(&m);`
                                       -> ntruplus<N>_officialopt_invntt_crep(&m)
  src/kem_lazy_r2fold_shoup.c          Encap `poly_basemul(&c, &h, &r)` -> basemul_shoup(&c, &r, &h),
                                       Decap `poly_basemul(&f, &c, &hinv)` -> basemul_shoup(&f, &c, &hinv)
                                       (signature (out, a lazy, b canonical); keygen nor2 and the
                                       Decap poly_basemul_scale unchanged)
  src/kem_lazy_r2fold_invcrep_shoup.c  both
plus the two prototypes.  Every other line is unchanged.

Overlay chains: exact copies of the committed current-best chain files with the #include
target renamed (and the header comment replaced), so each variant is the current best with
only the named call sites rebound:
  NTRU+864 / 1152 (S = codec_direct / freeze2op):
    src/kem_lazy_r2fold_<X>_S_keccak.c      <- src/kem_lazy_r2fold_S_keccak.c
    src/kem_lazy_r2fold_<X>_S_keccak_ht.c   <- src/kem_lazy_r2fold_S_keccak_ht.c
  NTRU+768 (S = freeze2op; the current best's HT inverse head only where the Decap inverse
  is still poly_invntt_scale, i.e. X = shoup):
    src/kem_lazy_r2fold_<X>_freeze2op_keccak.c, ..._keccak_ht.c, and
    src/kem_lazy_r2fold_shoup_freeze2op_keccak_ht_htinv.c
Variants (X): candidate invcrep_shoup, controls invcrep (invd_only), shoup (shoup_only).

  generate_invshoup_kems.py --param N --experiment . [--check] [--meta out.json]
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

VARIANTS = ("invcrep", "shoup", "invcrep_shoup")
STEM = {768: "freeze2op", 864: "codec_direct", 1152: "freeze2op"}


def sha(b):
    return hashlib.sha256(b).hexdigest()


def edit(text, old, new, count, what):
    if text.count(old) != count:
        raise ValueError(f"{what}: anchor occurs {text.count(old)} times, expected {count}")
    return text.replace(old, new)


def kem_body(n, base, variant):
    p = f"ntruplus{n}_officialopt"
    inv, shoup = "invcrep" in variant, "shoup" in variant
    head = ["/*", f" * GENERATED by common/official_opt_invshoup/tools/generate_invshoup_kems.py --param {n} "
                  "-- do not edit.",
            f" * src/kem_lazy_r2fold.c (current-best KEM body) with"]
    if inv:
        head.append(f" * the Decap poly_invntt_scale + poly_crepmod3 pair -> {p}_invntt_crep (one call)")
    if shoup:
        head.append(f" * {'and ' if inv else ''}the Encap BaseMul and the second Decap BaseMul -> {p}_basemul_shoup")
    head += [" * (out, lazy a, canonical b).  Every other line unchanged.", " */", ""]
    t = base
    proto = f"void {p}_basemul_nor2(poly *, const poly *, const poly *);\n"
    extra = ""
    if inv:
        extra += f"void {p}_invntt_crep(poly *);\n"
    if shoup:
        extra += f"void {p}_basemul_shoup(poly *, const poly *, const poly *);\n"
    t = edit(t, proto, proto + extra, 1, "prototype anchor")
    if inv:
        t = edit(t, "\tpoly_basemul_scale(&m, &c, &f);\n\tpoly_invntt_scale(&m);\n\tpoly_crepmod3(&m);\n",
                 f"\tpoly_basemul_scale(&m, &c, &f);\n\t{p}_invntt_crep(&m);\n", 1, "Decap inverse")
    if shoup:
        t = edit(t, "    poly_basemul(&c, &h, &r);\n", f"    {p}_basemul_shoup(&c, &r, &h);\n", 1, "Encap BaseMul")
        t = edit(t, "\tpoly_basemul(&f, &c, &hinv);\n", f"\t{p}_basemul_shoup(&f, &c, &hinv);\n", 1,
                 "Decap BaseMul")
    counts = {"poly_invntt_scale(": t.count("poly_invntt_scale("), "poly_crepmod3(": t.count("poly_crepmod3("),
              "poly_basemul(": t.count("poly_basemul("), "poly_basemul_scale(": t.count("poly_basemul_scale("),
              f"{p}_basemul_nor2(": t.count(f"{p}_basemul_nor2("),
              f"{p}_invntt_crep(": t.count(f"{p}_invntt_crep("),
              f"{p}_basemul_shoup(": t.count(f"{p}_basemul_shoup(")}
    want = {"poly_invntt_scale(": 0 if inv else 1, "poly_crepmod3(": 0 if inv else 1,
            "poly_basemul(": 0 if shoup else 2, "poly_basemul_scale(": 1, f"{p}_basemul_nor2(": 3,
            f"{p}_invntt_crep(": 2 if inv else 0, f"{p}_basemul_shoup(": 3 if shoup else 0}
    if counts != want:
        raise ValueError(f"{variant}: call counts {counts} != {want}")
    return "\n".join(head) + t, counts


def overlay(n, root, src_name, variant, include_old, include_new, label):
    text = (root / "src" / src_name).read_text()
    if not text.startswith("/*\n") or text.count(" */\n") != 1:
        raise ValueError(f"{src_name}: unexpected comment shape")
    body = text[text.index(" */\n") + 4:]
    if body.count(include_old) != 1 or not body.endswith(include_old):
        raise ValueError(f"{src_name}: include {include_old!r} not last")
    body = body[:-len(include_old)] + include_new
    head = ["/*", f" * GENERATED by common/official_opt_invshoup/tools/generate_invshoup_kems.py --param {n} "
                  "-- do not edit.",
            f" * NTRU+{n} AVX2 {label}: src/{src_name} (current-best chain, unchanged lines)",
            f" * with its #include rebound to the {variant} KEM body.", " */"]
    return "\n".join(head) + "\n" + body


def derive(root, n):
    stem = STEM[n]
    base = (root / "src/kem_lazy_r2fold.c").read_text()
    out, info = {}, {}
    labels = {"invcrep_shoup": "candidate (current best + Inverse D + Shoup BaseMul)" if n != 768 else
                               "variant current best + fused inverse + Shoup BaseMul",
              "invcrep": "control invd_only (current best + fused inverse)",
              "shoup": "control shoup_only (current best + Shoup BaseMul)" if n != 768 else
                       "candidate/control shoup (current best + Shoup BaseMul)"}
    for v in VARIANTS:
        body, counts = kem_body(n, base, v)
        out[f"src/kem_lazy_r2fold_{v}.c"] = body
        info[v] = counts
        k1 = f"kem_lazy_r2fold_{v}_{stem}_keccak.c"
        out[f"src/{k1}"] = overlay(n, root, f"kem_lazy_r2fold_{stem}_keccak.c", v, '#include "kem_lazy_r2fold.c"\n',
                                   f'#include "kem_lazy_r2fold_{v}.c"\n', labels[v])
        k2 = f"kem_lazy_r2fold_{v}_{stem}_keccak_ht.c"
        out[f"src/{k2}"] = overlay(n, root, f"kem_lazy_r2fold_{stem}_keccak_ht.c", v,
                                   f'#include "kem_lazy_r2fold_{stem}_keccak.c"\n', f'#include "{k1}"\n', labels[v])
        if n == 768 and v == "shoup":
            out[f"src/kem_lazy_r2fold_{v}_{stem}_keccak_ht_htinv.c"] = overlay(
                n, root, f"kem_lazy_r2fold_{stem}_keccak_ht_htinv.c", v,
                f'#include "kem_lazy_r2fold_{stem}_keccak_ht.c"\n', f'#include "{k2}"\n', labels[v])
    inputs = [f"src/kem_lazy_r2fold.c", f"src/kem_lazy_r2fold_{stem}_keccak.c", f"src/kem_lazy_r2fold_{stem}_keccak_ht.c"]
    if n == 768:
        inputs.append(f"src/kem_lazy_r2fold_{stem}_keccak_ht_htinv.c")
    meta = {"parameter": n, "inputs_sha256": {p: sha((root / p).read_bytes()) for p in inputs},
            "output_sha256": {p: sha(t.encode()) for p, t in sorted(out.items())}, "call_counts": info}
    return out, meta


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--param", type=int, choices=(768, 864, 1152), required=True)
    ap.add_argument("--experiment", type=Path, required=True)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--meta", type=Path)
    args = ap.parse_args()
    root = args.experiment.resolve()
    out, meta = derive(root, args.param)
    bad = 0
    for rel, text in sorted(out.items()):
        path = root / rel
        if args.check:
            if not path.exists() or path.read_text() != text:
                print(f"MISMATCH vs regeneration: {rel}", file=sys.stderr)
                bad += 1
            else:
                print(f"ok {rel}")
        else:
            path.write_text(text)
            print(f"wrote {rel}")
    if args.meta:
        args.meta.parent.mkdir(parents=True, exist_ok=True)
        args.meta.write_text(json.dumps(meta, indent=1, sort_keys=True) + "\n")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
