# Production GT variant macro source-of-truth.
#
# Keep this file make-only: it is included both by the local scheme Makefile
# and by aarch64-bench through $(NTRUPLUS)/gt_production_variants.mk.

GT_PRODUCTION_COMMON_FLAGS = \
	-DGT_PRODUCTION_RMINUS1_IS_POLY_API \
	-DGT_PRODUCTION_USE_RMINUS1_DECAP \
	-DGT_PRODUCTION_USE_DECAP_CANONICAL_POINTWISE

GT_PRODUCTION_DIRECT32_Q31_FLAGS = \
	-DGT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP

GT_PRODUCTION_SERIALIZATION_FLAGS = \
	-DGT_PRODUCTION_USE_CANONICAL_UNPACK_U1

GT_PRODUCTION_DISABLE_KEYGEN_SAMPLE_NTT_MUL3 ?= 0
GT_PRODUCTION_DISABLE_HIERK8_TREE ?= 0
GT_PRODUCTION_USE_PAPER_HIER_K8 ?= 0
GT_PRODUCTION_USE_INVNTT_LAZY_TWIDDLE1_LEN16 ?= 1
GT_PRODUCTION_USE_SECTION_GC ?= 1

# Production targets compile and link in one compiler invocation. Put each
# function/data object in its own section so the final link can discard source
# closure that no selected KEM entry point reaches. Set the policy to zero only
# when reproducing the historical non-GC binary.
ifeq ($(GT_PRODUCTION_USE_SECTION_GC),1)
GT_PRODUCTION_SECTION_GC_FLAGS = \
	-ffunction-sections \
	-fdata-sections \
	-Wl,--gc-sections
else ifeq ($(GT_PRODUCTION_USE_SECTION_GC),0)
GT_PRODUCTION_SECTION_GC_FLAGS =
else
$(error unknown GT_PRODUCTION_USE_SECTION_GC=$(GT_PRODUCTION_USE_SECTION_GC); use 0 or 1)
endif

# Direct-CQ is the mainline production default and matches the standalone
# release. Preserve the historical boolean only as an explicit compatibility
# input for older benchmark commands.
ifeq ($(origin GT_PRODUCTION_KEYGEN_LAYOUT),undefined)
ifneq ($(origin GT_PRODUCTION_USE_BPQ_CQ_KEYGEN),undefined)
GT_PRODUCTION_KEYGEN_LAYOUT := \
	$(if $(filter 1,$(GT_PRODUCTION_USE_BPQ_CQ_KEYGEN)),mixed,legacy)
else
GT_PRODUCTION_KEYGEN_LAYOUT := cq
endif
endif

ifeq ($(GT_PRODUCTION_KEYGEN_LAYOUT),cq)
GT_PRODUCTION_USE_BPQ_CQ_KEYGEN := 0
GT_PRODUCTION_KEYGEN_LAYOUT_FLAGS = \
	-DGT_PRODUCTION_USE_KEYGEN_CQ
GT_PRODUCTION_BPQ_CQ_KEYGEN_FLAGS =
GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS =
else ifeq ($(GT_PRODUCTION_KEYGEN_LAYOUT),mixed)
GT_PRODUCTION_USE_BPQ_CQ_KEYGEN := 1
GT_PRODUCTION_BPQ_CQ_KEYGEN_FLAGS = \
	-DGT_PRODUCTION_USE_BPQ_CQ_KEYGEN
GT_PRODUCTION_KEYGEN_LAYOUT_FLAGS = \
	$(GT_PRODUCTION_BPQ_CQ_KEYGEN_FLAGS)
GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS =
else ifeq ($(GT_PRODUCTION_KEYGEN_LAYOUT),legacy)
GT_PRODUCTION_USE_BPQ_CQ_KEYGEN := 0
GT_PRODUCTION_BPQ_CQ_KEYGEN_FLAGS =
GT_PRODUCTION_KEYGEN_LAYOUT_FLAGS =
ifeq ($(GT_PRODUCTION_DISABLE_KEYGEN_SAMPLE_NTT_MUL3),1)
GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS =
else
GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS = \
	-DGT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3
endif
else
$(error unknown GT_PRODUCTION_KEYGEN_LAYOUT=$(GT_PRODUCTION_KEYGEN_LAYOUT); use mixed, cq, or legacy)
endif

ifeq ($(GT_PRODUCTION_USE_PAPER_HIER_K8),1)
GT_PRODUCTION_HIERK8_TREE_FLAGS =
GT_PRODUCTION_PAPER_HIER_K8_FLAGS = \
	-DGT_BASEINV_USE_PAPER_HIER_K8 \
	-DGT_BASEINV_PAPER_HIER_K8_ONLY \
	-DGT_BASEINV_SCALED_R_EXTERNAL_BACKEND
else ifeq ($(GT_PRODUCTION_DISABLE_HIERK8_TREE),1)
GT_PRODUCTION_HIERK8_TREE_FLAGS =
GT_PRODUCTION_PAPER_HIER_K8_FLAGS =
else
GT_PRODUCTION_HIERK8_TREE_FLAGS = \
	-DGT_BASEINV_USE_HIER_K8_TREE \
	-DGT_BASEINV_SCALED_R_EXTERNAL_BACKEND
GT_PRODUCTION_PAPER_HIER_K8_FLAGS =
endif

GT_PRODUCTION_GENERIC_API_FLAGS = \
	-DGT_BASEINV_BATCH_USE_ASM_FINISH \
	-DGT_BASEINV_USE_FQINV15_ASM \
	-DGT_BASEINV_USE_HIER_K8 \
	$(GT_PRODUCTION_HIERK8_TREE_FLAGS) \
	$(GT_PRODUCTION_PAPER_HIER_K8_FLAGS)

ifneq ($(filter mixed cq,$(GT_PRODUCTION_KEYGEN_LAYOUT)),)
GT_PRODUCTION_LEGACY_KEYGEN_FLAGS =
else
GT_PRODUCTION_LEGACY_KEYGEN_FLAGS = \
	-DGT_PRODUCTION_USE_SCALED_KEYPAIR \
	-DGT_PRODUCTION_USE_KEYGEN_CANONICAL_PACK_P1 \
	$(GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS) \
	$(GT_PRODUCTION_GENERIC_API_FLAGS)
endif

GT_PRODUCTION_NO_Q31_FLAGS = \
	$(GT_PRODUCTION_COMMON_FLAGS) \
	$(GT_PRODUCTION_KEYGEN_LAYOUT_FLAGS) \
	$(GT_PRODUCTION_LEGACY_KEYGEN_FLAGS) \
	$(GT_PRODUCTION_SERIALIZATION_FLAGS) \
	$(GT_PRODUCTION_SECTION_GC_FLAGS)
GT_PRODUCTION_Q31_FLAGS = \
	$(GT_PRODUCTION_COMMON_FLAGS) \
	$(GT_PRODUCTION_KEYGEN_LAYOUT_FLAGS) \
	$(GT_PRODUCTION_LEGACY_KEYGEN_FLAGS) \
	$(GT_PRODUCTION_DIRECT32_Q31_FLAGS) \
	$(GT_PRODUCTION_SERIALIZATION_FLAGS) \
	$(GT_PRODUCTION_SECTION_GC_FLAGS)

GT_PRODUCTION_DEFAULT_VARIANT ?= gt_production_q31

ifeq ($(GT_PRODUCTION_DEFAULT_VARIANT),gt_production_q31)
GT_PRODUCTION_DEFAULT_FLAGS = \
	$(GT_PRODUCTION_Q31_FLAGS) \
	$(GT_PRODUCTION_DECAP_VERIFY_PROFILE_FLAGS)
else ifeq ($(GT_PRODUCTION_DEFAULT_VARIANT),gt_production_no_q31)
GT_PRODUCTION_DEFAULT_FLAGS = \
	$(GT_PRODUCTION_NO_Q31_FLAGS) \
	$(GT_PRODUCTION_DECAP_VERIFY_PROFILE_FLAGS)
else
$(error unknown GT_PRODUCTION_DEFAULT_VARIANT=$(GT_PRODUCTION_DEFAULT_VARIANT); use gt_production_q31 or gt_production_no_q31)
endif
