# Production GT variant macro source-of-truth.
#
# Keep this file make-only: it is included both by the local scheme Makefile
# and by aarch64-bench through $(NTRUPLUS)/gt_production_variants.mk.

GT_PRODUCTION_COMMON_FLAGS = \
	-DGT_PRODUCTION_USE_SCALED_KEYPAIR \
	-DGT_PRODUCTION_USE_RMINUS1_DECAP \
	-DGT_BASEINV_BATCH_USE_ASM_FINISH \
	-DGT_BASEINV_USE_FQINV15_ASM \
	-DGT_BASEINV_USE_HIER_K8

GT_PRODUCTION_DIRECT32_Q31_FLAGS = \
	-DGT_PRODUCTION_USE_DIRECT32_Q31_BASEMUL_ADD_ENCAP

GT_PRODUCTION_DISABLE_KEYGEN_SAMPLE_NTT_MUL3 ?= 0
GT_PRODUCTION_DISABLE_HIERK8_TREE ?= 0
GT_PRODUCTION_USE_INVNTT_LAZY_TWIDDLE1_LEN16 ?= 1

ifeq ($(GT_PRODUCTION_DISABLE_KEYGEN_SAMPLE_NTT_MUL3),1)
GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS =
else
GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS = \
	-DGT_PRODUCTION_USE_KEYGEN_SAMPLE_NTT_MUL3
endif

ifeq ($(GT_PRODUCTION_DISABLE_HIERK8_TREE),1)
GT_PRODUCTION_HIERK8_TREE_FLAGS =
else
GT_PRODUCTION_HIERK8_TREE_FLAGS = \
	-DGT_BASEINV_USE_HIER_K8_TREE
endif

GT_PRODUCTION_NO_Q31_FLAGS = \
	$(GT_PRODUCTION_COMMON_FLAGS) \
	$(GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS) \
	$(GT_PRODUCTION_HIERK8_TREE_FLAGS)
GT_PRODUCTION_Q31_FLAGS = \
	$(GT_PRODUCTION_COMMON_FLAGS) \
	$(GT_PRODUCTION_SAMPLE_NTT_TRIPLE_FLAGS) \
	$(GT_PRODUCTION_HIERK8_TREE_FLAGS) \
	$(GT_PRODUCTION_DIRECT32_Q31_FLAGS)

GT_PRODUCTION_DEFAULT_VARIANT ?= gt_production_q31

ifeq ($(GT_PRODUCTION_DEFAULT_VARIANT),gt_production_q31)
GT_PRODUCTION_DEFAULT_FLAGS = $(GT_PRODUCTION_Q31_FLAGS)
else ifeq ($(GT_PRODUCTION_DEFAULT_VARIANT),gt_production_no_q31)
GT_PRODUCTION_DEFAULT_FLAGS = $(GT_PRODUCTION_NO_Q31_FLAGS)
else
$(error unknown GT_PRODUCTION_DEFAULT_VARIANT=$(GT_PRODUCTION_DEFAULT_VARIANT); use gt_production_q31 or gt_production_no_q31)
endif
